version: '3' # vs mais atual
networks:
  word-cloud:
    driver: bridge
services:             

  app:
    build: app
    container_name: word-cloud-spotify-app
    restart: always
    tty: true
    networks:
      - word-cloud
    ports:
      - "3333:3333"
    volumes:       
      - ./app:/src/app
    working_dir: /src/app
    environment:
     - CHOKIDAR_USEPOLLING=true